[build]
  # Diretório de publicação (raiz do projeto)
  publish = "."
  
  # Comando de build (não necessário para site estático)
  command = ""

[build.environment]
  # Versão do Node.js (caso necessário)
  NODE_VERSION = "18"

# Configurações de redirecionamento
[[redirects]]
  # Redirecionar todas as rotas não encontradas para index.html (SPA)
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para arquivos estáticos
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
